### ISSUE TITLE
End results graph plotting

### ISSUE THREAD

**Issue by RabiaMubeen** [ValerianRey/fed_iot_guard#26]
Hey Valerian, i hope you are dong well. i want to know that how you have plotted the graphs which you have showed in your paper? can you please add the code for plotting end results of your work? I want to map final results of your work on my own test cases.

**Comment by ValerianRey** [comment]
Hi! The code used to plot those graphs is inside of [this notebook](https://github.com/ValerianRey/fed_iot_guard/blob/main/Test%20results.ipynb) (fed_iot_guard/Test Results.ipynb).
