### ISSUE TITLE
Problems running the script

### ISSUE THREAD

**Issue by avuminhas05** [ValerianRey/fed_iot_guard#28]
Program is exiting after reading the data. No results. Am i missing something or the code is incomplete?

**Comment by ValerianRey** [comment]
Did you do all of the steps listed in README.md?
What are the exact program arguments that you used?
Can you share the exit message / stack trade that you had when trying to run the code?

**Comment by atif19663** [comment]
Hello, hope you are feeling good. I had to try too much, but don't know why I'm stuck. Can you please help me? Will share where I'm stuck.
![image](https://user-images.githubusercontent.com/64259227/217022657-2a0b263f-6604-4fda-9c36-ba2e849447c6.png)
![code](https://user-images.githubusercontent.com/64259227/217022749-5b097b91-4858-42b2-a7f7-4f69c60647e2.PNG)

**Comment by atif19663** [comment]
And sometimes they show me this error if I run it using anaconda prompt.
![image](https://user-images.githubusercontent.com/64259227/217023399-6d255f10-3fdd-4596-9f87-a43ac358fa89.png)

**Comment by atif19663** [comment]
And can you please help me to see the output in a finite time because I had run it on different laptops but did not show any output yet? I had removed some rows and columns from datasets manually, but failed.

**Comment by avuminhas05** [comment]
> Did you do all of the steps listed in README.md? What are the exact program arguments that you used? Can you share the exit message / stack trade that you had when trying to run the code?

Yes I followed the exact steps mentioned in README.md.
I am getting this output after running the command : _"python src/main.py decentralized autoencoder --test --fedavg --collaborative --verbose-depth=2"_ :
_![image](https://user-images.githubusercontent.com/25576267/219855825-12d83798-fad6-44dd-84ad-db2483fbd2ad.png)_

I tried debugging the code, it seems like it's not doing anything after reading the data. I don't know what's the problem, I am stuck.

**Comment by avuminhas05** [comment]
Hi @ValerianRey , need help from you. I shared the output above. There is no error, but the process is killed. I don't know whether the code ran successfully or not.

**Comment by ValerianRey** [comment]
> Hi @ValerianRey , need help from you. I shared the output above. There is no error, but the process is killed. I don't know whether the code ran successfully or not. ![image](https://user-images.githubusercontent.com/25576267/224534522-53e0433e-2ac3-4e2d-97aa-99215a73056e.png) I also added a log in model_aggregation() function, but it's not printing. That means its not executing. Please help me out here.

How much RAM do you have? On my laptop, I see that about 13 GB of RAM are used after the data is loaded (I have 32 GB so I never noticed that this could be an issue).

**Comment by ValerianRey** [comment]
I just reinstalled everything to make the test from a clean install (Ubuntu 20.04, Python 3.9.16, fresh virtual environment with just the required libraries, installed using `pip installed -r requirements.txt`). Running `python src/main.py decentralized autoencoder --test --fedavg --collaborative --verbose-depth=2` gives, after about 5 minutes, the following output:
```bash


					FEDAVG DECENTRALIZED AUTOENCODER TESTING

Using CPU
Federation params: {'aggregation_function': <function federated_averaging at 0x7f4866be5ee0>, 'resampling': None, 'federation_rounds': 30, 'gamma_round': 0.75}
[{'clients_devices': [[1], [2], [3], [4], [5], [6], [7], [8]], 'test_devices': [0]}, {'clients_devices': [[0], [2], [3], [4], [5], [6], [7], [8]], 'test_devices': [1]}, {'clients_devices': [[0], [1], [3], [4], [5], [6], [7], [8]], 'test_devices': [2]}, {'clients_devices': [[0], [1], [2], [4], [5], [6], [7], [8]], 'test_devices': [3]}, {'clients_devices': [[0], [1], [2], [3], [5], [6], [7], [8]], 'test_devices': [4]}, {'clients_devices': [[0], [1], [2], [3], [4], [6], [7], [8]], 'test_devices': [5]}, {'clients_devices': [[0], [1], [2], [3], [4], [5], [7], [8]], 'test_devices': [6]}, {'clients_devices': [[0], [1], [2], [3], [4], [5], [6], [8]], 'test_devices': [7]}, {'clients_devices': [[0], [1], [2], [3], [4], [5], [6], [7]], 'test_devices': [8]}]
Reading data
█ [1/9] Data from Danmini_Doorbell
█ [2/9] Data from Ecobee_Thermostat
█ [3/9] Data from Ennio_Doorbell
█ [4/9] Data from Philips_B120N10_Baby_Monitor
█ [5/9] Data from Provision_PT_737E_Security_Camera
█ [6/9] Data from Provision_PT_838_Security_Camera
█ [7/9] Data from Samsung_SNH_1011_N_Webcam
█ [8/9] Data from SimpleHome_XCS7_1002_WHT_Security_Camera
█ [9/9] Data from SimpleHome_XCS7_1003_WHT_Security_Camera

Configuration [1/9]: {'clients_devices': [[1], [2], [3], [4], [5], [6], [7], [8]], 'test_devices': [0]}
█ Run [1/5]
█ █ Malicious clients: []
█ █ Computing the normalization values for each client
█ █ Federation round [1/30]

**Comment by ValerianRey** [comment]
> And sometimes they show me this error if I run it using anaconda prompt. ![image](https://user-images.githubusercontent.com/64259227/217023399-6d255f10-3fdd-4596-9f87-a43ac358fa89.png)

It take a lot of time to execute the whole script. Use a higher verbose depth to have more details about the current state of the training. (Like `--verbose-depth=4` or `--verbose-depth=5`). Otherwise it will look like it's not progression, while in reality it's just really slowly progressing.
