### ISSUE TITLE
Dataset Not available at link

### ISSUE THREAD

**Issue by eashishkalra** [ValerianRey/fed_iot_guard#30]
Hi

Dataset mentioned is not available at link. 
https://archive.ics.uci.edu/ml/machine-learning-databases/00442/

Kindly share correct dataset path and also what folders are expected in this dataset.
Does https://archive.ics.uci.edu/static/public/442/detection+of+iot+botnet+attacks+n+baiot.zip will work or not?

**Comment by ValerianRey** [comment]
Hey,
The link seems to be broken, thanks for pointing this out. I think the link you are suggesting works. I updated the readme.
